name: Workflow
on:
  push:
    branches: [ main ]
    tags:
      - v**
  pull_request: { }

jobs:
  required-meta:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check-commits:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v3
    with:
      build-tool: uv
      python-version: "3.13"

  lint:
    strategy:
      matrix:
        python-version: [ "3.13", "3.12", "3.11" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v3
    with:
      build-tool: uv
      cache-key-suffix: ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}

  test:
    strategy:
      matrix:
        python-version: [ "3.13", "3.12", "3.11" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v3
    with:
      build-tool: uv
      cache-key-suffix: ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      submit-coverage: ${{ matrix.python-version == '3.11' }}
      tests-selector: not local
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-migrations-postgres:
    strategy:
      matrix:
        postgres-version: [ "14", "15", "16" ]
    runs-on: ubuntu-24.04
    container: flyway/flyway:11.1
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - run: flyway migrate -skipCheckForUpdate
        working-directory: migrations/postgres
        env:
          FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres
          FLYWAY_USER: postgres
          FLYWAY_PASSWORD: postgres

  test-migrations-sqlite:
    runs-on: ubuntu-24.04
    container: flyway/flyway:11.1
    steps:
      - uses: actions/checkout@v4
      - run: flyway migrate -skipCheckForUpdate
        working-directory: migrations/sqlite

  extract-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.extract.outputs.version }}
    env:
      # renovate: datasource=pypi depName=uv versioning=semver-coerced
      UV_VERSION: 0.5.11
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          version: ${{ env.UV_VERSION }}
      - name: Read version from pyproject.toml
        id: extract
        run: |
          VERSION=$(uvx --from=toml-cli toml get --toml-path pyproject.toml project.version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build-migrations-container-image:
    needs:
      - extract-version
      - lint
      - test
      - test-migrations-postgres
      - test-migrations-sqlite
    strategy:
      matrix:
        sql-dialect: [ "postgres", "sqlite" ]
        platform: [ "arm64", "amd64" ]
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v5
    with:
      additional-build-args: |
        DIALECT=${{ matrix.sql-dialect }}
      context: 'migrations'
      digest-artifact-name: digests-${{ matrix.sql-dialect }}
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-2404-arm64-2x' || 'ubuntu-24.04' }}
      push-image: ${{ startsWith(github.ref, 'refs/tags/v') }}
      image-name: rate-limiter-migrations-${{ matrix.sql-dialect }}
      version: ${{ needs.extract-version.outputs.version }}
      tag-suffix: -${{ matrix.platform }}

  merge-migrations-container-image:
    if: success() && startsWith(github.ref, 'refs/tags/v')
    needs:
      - extract-version
      - build-migrations-container-image
    strategy:
      matrix:
        sql-dialect: [ "postgres", "sqlite" ]
    uses: preparingforexams/actions-container/.github/workflows/merge-manifests.yml@v5
    with:
      image-name: rate-limiter-migrations-${{ matrix.sql-dialect }}
      tag: ${{ needs.extract-version.outputs.version }}
      variant-digests: digests-${{ matrix.sql-dialect }}

  publish-package:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/publish-package.yml@v3
    needs:
      - lint
      - test
      - test-migrations-postgres
      - test-migrations-sqlite
    if: success() && startsWith(github.ref, 'refs/tags/v')
    with:
      build-tool: uv
      cache-key-suffix: '3.11'
      python-version: '3.11'
      pypi-username: ${{ vars.PYPI_USERNAME }}
    secrets:
      pypi-password: ${{ secrets.PYPI_PASSWORD }}
