name: Workflow
on: [ push ]

jobs:
  lint:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.10", "3.9" ]
    container: python:${{ matrix.pyversion }}-slim
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        run: pip install poetry==1.2.2
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Check coding standards
        run: |
          poetry run black --check src/
          poetry run flake8 src/
          poetry run mypy src/

  test:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.10", "3.9" ]
    container: python:${{ matrix.pyversion }}-slim
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        run: pip install poetry==1.2.2
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Run tests
        run: poetry run pytest src/


  push_migrations_docker:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry==1.2.2
      - name: Use Poetry to read version
        run: |
          VERSION=$(poetry version --short)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/preparingforexams/rate-limiter-migrations:${{ env.VERSION }} migrations
      - name: Push the tagged Docker image
        run: docker push ghcr.io/preparingforexams/rate-limiter-migrations:${{ env.VERSION }}

  publish_package:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    needs:
      - lint
      - test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    env:
      TWINE_USERNAME: rate_limiter
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Install Poetry
        run: pip install poetry
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Build project
        run: poetry build
      - name: Upload to pypi registry
        run: poetry run twine upload --non-interactive --repository-url https://pypi.bjoernpetersen.net dist/*
